# MongoDB Service — ClusterIP (internal only)
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: taskflow
    tier: database
spec:
  type: ClusterIP
  selector:
    app: taskflow
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
